export const CHANGE_VOICE = 'CHANGE_VOICE';
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const REFRESH_APP = 'REFRESH_APP';
export const CHANGE_VOICE_CHARACTER = 'CHANGE_VOICE_CHARACTER';
export const CHANGE_AVATAR = 'CHANGE_AVATAR';
export const EDIT_APP_INFO = 'EDIT_APP_INFO';
